<?php
ini_set('display_errors', 1);
error_reporting(E_ALL);

require_once __DIR__ . '/vendor/autoload.php'; 
require './includes/db.php'; // Make sure this points to the correct DB

$query = "SELECT * FROM users";
$result = $conn->query($query);

$mpdf = new \Mpdf\Mpdf();
$mpdf->SetTitle('User Accounts Report');

$html = '<h2 style="text-align:center;">User Accounts Report</h2>';
$html .= '<table border="1" cellspacing="0" cellpadding="6" width="100%">';
$html .= '<thead>
    <tr style="background-color: #f2f2f2;">
        <th>ID</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Usertype</th>
    </tr>
</thead><tbody>';

if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $html .= '<tr>
            <td>' . $row['Name_id'] . '</td>
            <td>' . htmlspecialchars($row['phone']) . '</td>
            <td>' . htmlspecialchars($row['email']) . '</td>
            <td>' . htmlspecialchars($row['usertype']) . '</td>
        </tr>';
    }
} else {
    $html .= '<tr><td colspan="4" style="text-align:center;">No users found.</td></tr>';
}

$html .= '</tbody></table>';
$html .= '<br><div style="text-align:right;">Generated by: YURI NEIL BAYRON</div>';
$html .= '<br><div style="text-align:right;">Generated on: ' . date("Y-m-d H:i:s") . '</div>';

$mpdf->WriteHTML($html);
$filename = "users_report_" . date("Ymd_His") . ".pdf";
$mpdf->Output($filename, 'D'); // Download the file

$conn->close();
?>
